# This is a basic workflow to help you get started with Actions

name: UpdateData

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  data-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install curl and pdftohtml
      run: sudo apt-get install curl pdftohtml

    # Runs a single command using the runners shell
    - name: Update saude-sp-gov-br data
      run: bash src/saude-sp-gov-br.sh

#     - name: Commit results
#       run: |
#         git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
#         git pull github ${GITHUB_REF} --ff-only
#         git add .
#         git commit -m "Update native model"
#         git push github HEAD:${GITHUB_REF}
